food/urls.py
from django.urls import path
from food import views

app_name = 'food'

urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('<int:pk>/', views.DetailClassView.as_view(), name='detail'),
    path('create/', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:item_id>', views.update_item, name='update_item'),
    path('delete/<int:item_id>', views.delete_item, name='delete_item'),
]

online_food/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile_page, name='profile'),
]

urlpatterns += [
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_description = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length=500, default='https://cdn-icons-png.flaticon.com/512/1377/1377194.png')

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_pictures',
                              default='profilepic.jpg')
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from food.models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_description', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from food.models import Item
from food.forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


class DetailClassView(DetailView):
    model = Item
    template_name = 'food/detail.html'


def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    context = {
        "form": form,
    }

    return render(request, 'food/item_form.html', context)


class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_description', 'item_price', 'item_image']
    template_name = 'food/item_form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def update_item(request, item_id):
    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    context = {
        "form": form,
        "item": item,
    }

    return render(request, 'food/item_form.html', context)


def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    context = {
        "item": item,
    }

    return render(request, 'food/item_delete.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from users.forms import RegisterForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Welcome {username}, your account has been created successfully!')
            return redirect('login')

    form = RegisterForm()
    context = {
        'form': form,
    }
    return render(request, 'users/register.html', context)


@login_required
def profile_page(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Index - Food</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid px-5">
        <a class="navbar-brand" href="{% url "food:index" %}">Online Food</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url "food:create_item" %}">Add</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "profile" %}">Profile</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <form action="{% url "logout" %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-outline-success ms-5" type="submit">Logout</button>
                </form>
              </li>
            {% else %}
              <li class="nav-item">
              <a class="nav-link" href="{% url "login" %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "register" %}">Registration</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container py-3">
        <div class="text-center">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{message.tags}}">{{ message }}</div>
            {% endfor %}
          {% endif %}
        </div>
        {% block body %} {% endblock %}
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

food/templates/food/detail.html
{% extends "food/base.html" %}
{% block body %}
<div class="row">
    <div class="col-md-6">
        <img width="300px" src="{{object.item_image}}" alt="{{object.item_name}}">
    </div>
    <div class="col-md-6">
        <h3>{{object.item_name}}</h3>
        <h5>{{object.item_description}}</h5>
        <h6>${{object.item_price}}</h6>
        <a class='btn btn-danger mt-5' href="{% url "food:delete_item" object.id %}">Delete</a>
    </div>
</div>
{% endblock %}

food/templates/food/index.html
{% extends "food/base.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Index - Food</title>
  </head>
  <body>
    {% block body %}
    {% for item in item_list %}
      <div class="row mb-4">
        <div class="col-md-3 offset-md-2">
          <img
            height="150px"
            src="{{item.item_image}}"
            alt="{{item.item_name}}"
          />
        </div>
        <div class="col-md-4">
          <h3>{{item.item_name}}</h3>
          <h6 class="fw-lighter fst-italic">added by {{item.user_name}}</h6>
          <h5>{{item.item_description}}</h5>
          <h6>${{item.item_price}}</h6>
        </div>
        <div class="col-md-2">
          <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
      </div>
    {% endfor %}
    {% endblock %}
  </body>
</html>

food/templates/food/item_delete.html
{% extends "food/base.html" %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  <h3>Are you sure want to delete the item {{item.item_name}}</h3>
  <button class="btn btn-danger" type="submit">Delete</button>
</form>
{% endblock %}

food/templates/food/item_form.html
{% extends "food/base.html" %}
{% block body %}
<form method="POST" class="form">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="btn btn-success">Save</button>
</form>
{% endblock %}

users/templates/users/login.html
{% extends "food/base.html" %}
{% block body %}
<div class="card w-50 mx-auto">
  <div class="card-header">Log In</div>
  <div class="card-body">
    <form class="form" method="POST">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group">
            {{ field.name }}
            {{ field }}
        </div>
      {% endfor %}
      <button class="btn btn-success mt-3" type="submit">Login</button>
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends "food/base.html" %}
{% block body %}
<div class="alert alert-warning text-center p-5">
    <h2 class="mb-5">You have been loged out successfully!</h2>
    <a class="btn btn-success me-3" href="{% url "login" %}">Login</a>
    <a class="btn btn-success" href="{% url "register" %}">Registration</a>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "food/base.html" %}
{% block body %}
<div class="card w-50 p-3 mx-auto">
  <div class="card-body text-center">
    <img src="{{user.profile.image.url}}" alt="{{ user.username }}" width="150px" />
    <h1>{{ user.username }}</h1>
    <h6>{{user.profile.location}}</h6>
  </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "food/base.html" %}
{% block body %}
<div class="card w-50 mx-auto">
    <div class="card-header">Registration</div>
    <div class="card-body">
        <form class="form" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.name }}
                    {{ field }}
                </div>
            {% endfor %}
            <button class="btn btn-success mt-3" type="submit">Signup</button>
        </form>
    </div>
</div>
{% endblock %}